# Generated by Django 4.2.5 on 2023-09-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arrival",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fish", models.CharField(max_length=20)),
                ("weight", models.FloatField()),
                ("cost_per_unit", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "arrival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.arrival",
                    ),
                ),
            ],
        ),
    ]
